markdown  : maruku
permalink : pretty
pygments  : true
redirects : true
exclude   :
  - README.md

author      : Zach Williams, @zachwill
analytics   : UA-11117730-1
description : "Zach Williams is a superhero currently based in Portland."
