markdown  : maruku
permalink : pretty
pygments  : true
exclude   :
  - README.md

author      : Zach Williams, @zachwill
analytics   : UA-XXXXX-X
description : "A blank site description."
title       : Blog
